#!/bin/env bash
# alpine
# debian
# ubuntu

Path=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source ${Path}/function

setDNS(){
  rm -f /etc/resolv.conf > /dev/null 2>&1
  if getLocation
  then
    echo 'nameserver 223.5.5.5
nameserver 223.6.6.6
nameserver 2400:3200::1
nameserver 2400:3200:baba::1' > /etc/resolv.conf
  else
    echo 'nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001' > /etc/resolv.conf
  fi
}
setFont(){
  gitCR SourceHanSerif.ttc adobe-fonts/source-han-serif release OTC/SourceHanSerif-SemiBold.ttc
  if [ ! -d /usr/local/share/fonts ]
  then
    mkdir -p /usr/local/share/fonts
  fi
  mv SourceHanSerif.ttc /usr/local/share/fonts/SourceHanSerif.ttc
  fc-cache -f
  locale-gen zh_CN.UTF-8
  rm /etc/default/locale
  echo -e "LANG=zh_CN.UTF-8\nLANGUAGE=zh_CN:zh\nLC_ALL=zh_CN.UTF-8" > /etc/locale.conf
  ln -s /etc/locale.conf /etc/default/locale
}

UBUNTU_OPT(){
  log.info "正在配置 DNS"
  setDNS
  log.success "配置完成"
  log.info "正在切换 软件源"
  if getLocation
  then
    OldSource="ports.ubuntu.com"
    NewSource="mirrors.cernet.edu.cn"
  else
    OldSource="ports.ubuntu.com"
    NewSource="ports.ubuntu.com"
  fi
  sed -i "s|${OldSource}|${NewSource}|g" /etc/apt/sources.list
  log.success "切换完成"
  log.info "正在更新 软件源"
  apt update -y
  log.success "更新完成"
  log.info "正在更新 软件包"
  apt upgrade -y
  log.success "更新完成"
  log.info "正在更新 系统整体"
  apt full-upgrade -y
  log.success "更新完成"
  log.info "正在设置 中文环境"
  apt install -y fontconfig language-pack-zh-*
  setFont
  log.success "设置完成"
  log.info "正在安装 CA证书"
  apt reinstall -y ca-certificates
  log.success "安装完成"
  log.info "正在切换 https"
  if ! grep -q https /etc/apt/sources.list
  then
    sed -i "s|https|http|g" /etc/apt/sources.list
  fi
  apt update -y
  log.success "切换完成"
  log.info "正在安装 cURL"
  apt install -y curl
  log.success "安装完成"
}

DEBIAN_OPT(){
  log.info "正在配置 DNS"
  setDNS
  log.success "配置完成"
  log.info "正在切换 软件源"
  if getLocation
  then
    OldSource="deb.debian.org"
    NewSource="mirrors.cernet.edu.cn"
  else
    OldSource="deb.debian.org"
    NewSource="deb.debian.org"
  fi
  sed -i "s|${OldSource}|${NewSource}|g" /etc/apt/sources.list
  log.success "切换完成"
  log.info "正在更新 软件源"
  apt update -y
  log.success "更新完成"
  log.info "正在更新 软件包"
  apt upgrade -y
  log.success "更新完成"
  log.info "正在更新 系统整体"
  apt full-upgrade -y
  log.success "更新完成"
  log.info "正在设置 中文环境"
  apt install -y fontconfig locales
  sed -i \
  -e 's/^#\s*zh_CN.UTF-8 UTF-8/zh_CN.UTF-8 UTF-8/' \
  -e 's/^#\s*zh_HK.UTF-8 UTF-8/zh_HK.UTF-8 UTF-8/' \
  -e 's/^#\s*zh_SG.UTF-8 UTF-8/zh_SG.UTF-8 UTF-8/' \
  -e 's/^#\s*zh_TW.UTF-8 UTF-8/zh_TW.UTF-8 UTF-8/' \
  /etc/locale.gen
  setFont
  log.success "设置完成"
  log.info "正在安装 CA证书"
  apt reinstall -y ca-certificates
  log.success "安装完成"
  log.info "正在切换 https"
  if ! grep -q https /etc/apt/sources.list
  then
    sed -i "s|https|http|g" /etc/apt/sources.list
  fi
  apt update -y
  log.success "切换完成"
  log.info "正在安装 cURL"
  apt install -y curl
  log.success "安装完成"
}

if grep -iq Ubuntu /etc/issue || grep -iq Ubuntu /etc/os-release
then
  UBUNTU_OPT 
elif grep -iq Debian /etc/issue || grep -iq Debian /etc/os-release
then
  DEBIAN_OPT
else
  log.warn "其他系统暂时不支持"
fi