#!/bin/env bash
Path=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source ${Path}/function
source ${Path}/common

log.info "正在配置 DNS"
setDNS
log.success "配置完成"

log.info "正在切换 软件源"
if getLocation
then
  OldSource="deb.debian.org"
  NewSource="mirrors.cernet.edu.cn"
else
  OldSource="deb.debian.org"
  NewSource="deb.debian.org"
fi
sed -i "s|${OldSource}|${NewSource}|g" /etc/apt/sources.list
log.success "切换完成"

log.info "正在更新 软件源"
apt update -y
log.success "更新完成"
log.info "正在更新 软件包"
apt upgrade -y
log.success "更新完成"
log.info "正在更新 系统整体"
apt full-upgrade -y
log.success "更新完成"

log.info "正在安装 cURL"
apt install -y curl
log.success "安装完成"

log.info "正在安装 cURL"
apt install -y curl
log.success "安装完成"

log.info "正在设置 中文环境"
apt install -y fontconfig locales
sed -i \
-e 's/^#\s*zh_CN.UTF-8 UTF-8/zh_CN.UTF-8 UTF-8/' \
-e 's/^#\s*zh_HK.UTF-8 UTF-8/zh_HK.UTF-8 UTF-8/' \
-e 's/^#\s*zh_SG.UTF-8 UTF-8/zh_SG.UTF-8 UTF-8/' \
-e 's/^#\s*zh_TW.UTF-8 UTF-8/zh_TW.UTF-8 UTF-8/' \
/etc/locale.gen
setFont
log.success "设置完成"

log.info "正在设置 时区 "
setTimeZone
log.success "设置完成"

if dpkg -s ca-certificates > /dev/null 2>&1
then
  log.info "正在更新 CA证书"
  update-ca-certificates
  log.success "更新完成"
else
  log.info "正在安装 CA证书"
  apt reinstall -y ca-certificates
  update-ca-certificates
  log.success "安装完成"
fi

log.info "正在切换 https"
if ! grep -q https /etc/apt/sources.list
then
  sed -i "s|http|https|g" /etc/apt/sources.list
fi
apt update -y
log.success "切换完成"

rm ${Path}/function
rm ${Path}/common